from pyChatGPT import ChatGPT

session_token = 'eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..fLmc3uZQJKV4e4SK.NH72XwaMXvEGymxrpLFcj4y6kb9AX-BJmhysuVhb3AOOI3TgO9GzucjVuO7a7sq4z2wbXr8CKR0XTvv3TybcYkL0IU46MxXMUxh1bO_Xdfo0P43H9-Ekr8bmPezIgWNsf2Y0-sm-SR_QBE2gjlU8613-J7V9XoOueIQTZ1f8CW4i-vTw94cAzQD1TTPXC8-qzyOhJiyBjmQrkPcB6KRCuIvOKP-2bxQRl-sWlrplCeRZfu_yeGJXjZ9lhHkTNsfBvd8QgHBiOtwJxZgx1nW-cpeU2VeQ4UDyuoeaRR3f4akKpP9SRH3YrsbacDzbb2aHQGfPsq46FAy5ErrXnHIErIVsj-jXdCVdv__sEiEOMthcABSvq6o-xonW6-AYPW7e_pcngetBzPeJgiD_nRyw8m-4f9F9JS_mIsPtRK_95gXANRrkoQKDhQ5k-zN9BucNrRBJybiFpx14xPMOF2K0qvkGLM5cEgIxUiDyh9qcdwK5TStY8fZ5rcCO8UB-hxVlru68Qnwotzi2oc-urTx_nrAXsfBysN1dMOWmJ191IyvnOjRU9ssidHKAEPCEeNuKZ2w0a34MaWy6xSElkrIaj7GJbzZHv7430rRY6Fuxk153pD5f87_5UdDS_KWeJBy7gfDvpNMwCBsAQqp4lBQM9TlPEEOaLav5hbM2PigxokHD4W-uYcI5ztbCJ4a4mAiHQuPbATIUREpmLeEKVmVoELtfFNbJQimwh4DNtfsifSvB01-zZyK3nU7HQvD3vcRC2lD0zEbng_P4seHuRF18QjvBHGGhSb6e7UTBU9eqknB5Jiw-zIGwIc-VSdWWlNOsuN7Vatle21GKhkU2llwrNvrpgMWQUxZs9dfH5YnDnG-SVE6MGHPDFQHPw2Bnld0dDufLlPpbhnLrqwlSDDHn8rXNiS6MXegaFwLWJoUqAZHtqaTy_dqf6NNsc6YM_SAOa803viZAG62CB8TyQIpgE32GB5T099Lf0-dBQCiorAyB1tOsSwzCKkOG1UGYF_49RBDv2Z3VXfrL3aa15z2UBjrjjMfv1PQqc706SbwKcdR01xqseIEmHnCoSMqRE-sUMFjfMoukqy_pjQRJlOOCGDgm7Da6Sn-3s-OqwCeSWb-4dCFCuGn1S1QZs0J2DzxFSv5OSZCxmdCFRtIDgxr4KMP-iI30fFv_YZq_1Bu2DGElzgC8mXmeS1BWwMuWrfs9ferhp2WOd6Bn-mrSWG-48N-Pnj968VfOjhU3-IaMfMu7lUkvHj2mxzJaSL0Y4KosjScgn2Nj-6uGKWTL7jEyIGaP_4-9YUjQjV4yH_FHNuWRudKxYXfmKKErX806_UfS9-LJGkejirCDVelw3DnWUDaPIe2YMUj8wDn-KDcFZlHJscbC7dEEQC6ftprqk4KirPDuO0eKEAa9QYpGLqihm9d3F4CHti-ccvDFk48Hej2O-FJWm0WfLUL9cTq11_vUSxRLfrjpNBxErmP4dAg8_ZT8or034BDrr_tfN3zpLLU7dLiIbugy6qAnJzg5soHKvLB-x-W4tXFLpEwlymyKxKNWtOqSJVkOmYXy8hi7fX33o-h-lK8aTRMpu7AT7UJJEdzRhssElDyDTqx65PEEceTzUtuMsLt8v7Rx-yrkI42G2Kx0fickUwX4grz_VddhlCw6bSSNShAThdol4jOG4CMZFdPe1UDyHub49SSBZ53RTJ1xyXzF6LDSEcsxjH9R_TZhpdvkXdGjiEFHofG86s9_1cw1vZuoDct0KsGvTmxkcUtCRleskCB_TMNXMT4kIBR54Uk7D_yphMpDtZE27Wnb7YWCLXFsL0nd2Fm7wIjcKYfyatXjXGHlGPny4_KFVXIozzsxKGCyEWg0gwzM2srztuYb8F5cltIzeDR4CYhuLKSmOcC-c2NrMoSBNv75QCRUxtp7yVMFdNK9xddjWldr-q2PS8PcJzRuGbRtEQ2An6y6yxnJqptiSREghcL5cJI3Nh5utDCoYLMLs64rbWbDHnDizUDCM1dOT3OqJFbwLNEJASNwG7vYN9YGAOzcStw7KUpNfvMGNfd8bhtLOm3OI6ryOkMA0-7gFGuhx6ImharCYUhV4oY-wQDUqaYBsW1Onj6QVjh0aLyDnmuztRua7UnibY1O8cUqhTOot7l1OuVVX0bdjOFJU1HAJMRxGeuRjMd0dEzatJvuu-Y3BZruVLgA_OV-MmS0IKHgDZVyG6zN4VRw9m7gSgugg8WLY3XENAuEl80ETjUMu3cWRJceqeTgeYxKDppEsAQHX2JcnRSt4rPT5mtGBduX6iHdyTbwZEm9Prdx9oQiTYjVNV-Up1OEbgUM2E3H60rYbLNHlOkEN3afHNqztLhTlynN3zgj42aXhVB5PilcoYNPo6IkRfCFPPYGy5_5M2i9YqabnfzF2wMkDaTUPAUycvDFYoVTN7tZqK0w10egEdlSigxEzWUHMuzS5O3jbtq5p0muatrn0y0xda_pG_GOpUsx_GN2TgQuH0Ur65r3fBMel83_a9N5W3U9DdQKL-AVGjAEllKy-F75ApqSMKTE-a_qYsYAWQBKkZLx5q3-d0w3uX05o7LMYrYhnuJj1asgsvOy2cRC-jW1EEEC5qBQ2_mHqFnDhUfaRK5vqEV_0JLTIKbx9tOUAaSR0wjONTGyZtN2BQqBB3TRStKoraA.AjGcg3u3FhUc9I8RHytDnQ'

# with open('prompt_fx.txt', 'r') as file:
#         prompt_mn = file.read().rstrip()
# print(prompt_mn)

prompt = 'Tập đoàn Intel hiện đang xem xét tăng thêm đáng kể các khoản đầu tư vào Việt Nam để mở rộng nhà máy đóng gói và thử nghiệm chip, theo hai nguồn tin độc quyền mà Reuters có được. Số tiền tập đoàn công nghệ này có thể đầu tư rơi vào khoảng 1 tỷ USD, báo hiệu vai trò càng tăng của Việt Nam trong chuỗi cung ứng toàn cầu về chất bán dẫn khi các doanh nghiệp tìm cách giảm lệ thuộc vào Trung Quốc và Đài Loan giữa căng thẳng Mỹ - Trung. Một nguồn tin của Reuters khẳng định, khoản đầu tư này có thể sẽ được thực hiện "trong những năm tới" và thậm chí có thể lớn hơn 1 tỷ USD, trong khi nguồn tin thứ hai cho biết Intel cũng đang cân nhắc đầu tư thay thế vào Singapore và Malaysia, những nơi có thể được ưu tiên hơn Việt Nam. Cả hai nguồn đều yêu cầu giấu tên vì kế hoạch đầu tư vẫn chưa được công khai.  "Việt Nam là một phần quan trọng trong mạng lưới sản xuất toàn cầu của chúng tôi, nhưng chúng tôi chưa công bố bất kỳ khoản đầu tư mới nào", đại diện của Intel trả lời khi được Reuters hỏi về kế hoạch đầu tư khả thi. Nhà máy đóng gói và thử nghiệm chip của Intel tại Việt Nam có quy mô lớn nhất thế giới. Tập đoàn này ước tính đã đầu tư khoảng 1,5 tỷ USD cho đến nay. Việc mở rộng tại Việt Nam được cho là sẽ giúp Intel quản lý tốt hơn sự gián đoạn nguồn cung do phụ thuộc nhiều vào một quốc gia hoặc một nhà máy, theo một trong những nguồn tin nói với Reuters, trích dẫn các cuộc đàm phán nội bộ. Việt Nam đang tích cực đẩy mạnh mở rộng ngành sản xuất chip, thu hút các công ty nước ngoài trong cả ba phân khúc chính là lắp ráp, thử nghiệm và đóng gói; sản xuất bán dẫn (fabs); và thiết kế. Một quan chức trong ngành công nghiệp của Mỹ khẳng định Việt Nam có tiềm năng lớn để phát triển nhanh chóng trong lĩnh vực lắp ráp và thiết kế chip. Theo đó, cơ hội lớn nhất của Việt Nam là trong lĩnh vực lắp ráp chip là để đáp ứng nhu cầu của ngành nhằm giảm tình trạng "tập trung quá mức" năng lực sản xuất ở Trung Quốc và Đài Loan, hai thị trường chiếm 60% công suất toàn cầu. Trong khi đó, việc thiết kế chip đòi hỏi ít vốn hơn và nhiều công nhân có tay nghề cao hơn. Việt Nam cũng đạt nhiều bước tiến về trình độ nhân công, trong bối cảnh tập đoàn Synopsys (Mỹ) cũng đang hoạt động ở Việt Nam, và các doanh nghiệp như FPT và Viettel cũng đang mở rộng nhanh chóng. Gã khổng lồ chip và điện tử Samsung đã mở một cơ sở nghiên cứu tại Hà Nội vào cuối năm ngoái và có một nhà máy đóng gói chất bán dẫn tại Việt Nam. Sau tình trạng thiếu chất bán dẫn trên toàn cầu do đại dịch COVID-19, Intel đã công bố kế hoạch vào cuối năm 2021 để đầu tư hơn 7 tỷ USD để xây dựng một nhà máy thử nghiệm và đóng gói chip mới ở Malaysia. Cơ sở đó dự kiến sẽ bắt đầu sản xuất vào năm 2024. Intel cũng có các cơ sở thử nghiệm và đóng gói ở Trung Quốc và Mỹ. Tham khảo Reuters'
print("Text: ",prompt)
prompt_mn = 'Tóm tắt văn bản sau bằng Tiếng Việt chỉ dùng tối đa 200 từ. Văn bản: '+prompt
api = ChatGPT(session_token, verbose=True)

resp = api.send_message(prompt_mn)
print(resp['message'])